name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.4
        with:
          modrinth-id: oaoGrJ6t
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          files: |
            build/libs/!(*-@(dev|sources)).jar
          version-type: release
          version-name: "v${{ github.ref_name }}"
          loaders: fabric
          game-versions: "26.1"
          changelog-file: docs/更新公告_v2.0.0.md
          dependencies: |
            fabric-api | depends | *
            cloth-config | depends | *
            modmenu | optional | *

      - name: create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          body: |
            BF煎饼猫 v${{ github.ref_name }} 自动发布
            更新内容见 docs/更新公告_v2.0.0.md
